### ISSUE TITLE
Specify current date range on initialization

### ISSUE THREAD

**Issue by bennbollay** [iamPres/react-datepick#5]
Please expose a property that allows for the state of the component to be persisted across loads - for example, by including parameters in the URL.

The state supplied and stored may be opaque to the caller, but should result in the component entering the same absolute or relative time range (updated, accordingly, with the current time).

Example usage:
```js
import { useHistory } from "react-router-dom";

...

const persistRange = (range: string): void { 
  let history = useHistory();
  history.replace(`#range={range}`);
}

...

  persistedRange = history.location.hash.substring(1).split("=")[1];

  <DatePick
    getRawRange={persistRange}
    rawRange={persistedRange}
  />
```

**Comment by preston-willis** [comment]
Check out https://github.com/iamPres/react-datepick/pull/6

**Comment by bennbollay** [comment]
Close the issue when the change is submitted :)
